DROP TABLE IF EXISTS veggies CASCADE;
DROP TABLE IF EXISTS farmshares;

CREATE TABLE veggies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL 
);

CREATE TABLE farmshares (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    veggie_id BIGINT NOT NULL REFERENCES veggies(id)
);